name: C21-TW-BAD-PROJ
on:
    push:
        branches:
            - '*'
    workflow_dispatch:

env:
    POSTGRES_DB: bad_proj
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres

jobs:
    testing:
        runs-on: ubuntu-latest
        container: node:latest
        services:
            postgres:
                env:
                    POSTGRES_DB: ${{env.POSTGRES_DB}}
                    POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
                image: postgres
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v3
            - run: |
                  yarn install 
                  yarn knex migrate:latest --env test
                  yarn jest
