name: C21-TW-BAD-PROJ
on:
    push:
        branches:
            - '*'
    workflow_dispatch:

env:
    POSTGRES_DB: bad_proj
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres

jobs:
    testing:
        runs-on: ubuntu-latest
        container: node:latest
        services:
            postgres:
                env:
                    POSTGRES_DB: ${{env.POSTGRES_DB}}
                    POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
                image: postgres
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v3
            - run: |
                  yarn install 
                  yarn knex migrate:latest --env test
                  yarn knex seed:run --env test
                  yarn jest
    deploy:
        if: github.ref_name == 'production'
        runs-on: ubuntu-latest
        needs: testing
        steps:
            - name: ssh to pull latest version
              uses: fifsky/ssh-action@master
              with:
                  command: |
                      cd C21-TW-BAD-GROUP5
                      git pull origin main
                      yarn install
                      yarn knex migrate:latest --env production
                      yarn knex seed:run
                      forever restartall
                  host: samor.me
                  user: ubuntu
                  key: ${{secrets.SSH_PRIVATE_KEY}}
